# Generated by Django 3.2.6 on 2022-01-16 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('Barcode', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('Image', models.ImageField(default='default.png', upload_to='')),
                ('Tag', models.CharField(blank=True, max_length=100, null=True)),
                ('Minimum', models.IntegerField(default=0)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.unit')),
            ],
        ),
    ]
