# Generated by Django 3.2.6 on 2022-01-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Barcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
