# Generated by Django 3.2.6 on 2022-01-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='product_photo'),
        ),
    ]
