# Generated by Django 3.2.6 on 2022-01-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='Product.category'),
        ),
    ]
