# Generated by Django 3.2.6 on 2022-01-19 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0007_alter_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
        migrations.AddField(
            model_name='product',
            name='Cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Expected_Profit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Price', models.IntegerField()),
                ('Level', models.CharField(choices=[(1, 'Retail'), (2, 'Member')], max_length=6)),
                ('CreateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('Inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.product')),
            ],
        ),
    ]
