# Generated by Django 3.2.6 on 2022-01-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20220119_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Rate', models.IntegerField()),
                ('Note', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Base_Currency',
            field=models.CharField(choices=[('B', 'Baht'), ('K', 'Kyat')], default='B', max_length=4),
            preserve_default=False,
        ),
    ]
