# Generated by Django 3.2.6 on 2022-01-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20220119_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Base_Currency',
            field=models.CharField(choices=[('B', 'Baht'), ('K', 'Kyat')], default='B', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='product_photo/default.png', upload_to='product_photo'),
        ),
    ]
