# Generated by Django 3.2.6 on 2022-01-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_pricelist_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='Note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='Rate',
            field=models.FloatField(),
        ),
    ]
