# Generated by Django 3.2.6 on 2022-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_auto_20220121_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not available')], default='A', max_length=1),
        ),
    ]
