# Generated by Django 3.2.6 on 2022-01-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Expected_Profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Minimum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
