# Generated by Django 3.2.6 on 2022-01-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20220122_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='BuyingPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
