# Generated by Django 3.2.6 on 2022-01-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_product_buyingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BuyingPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
