# Generated by Django 3.2.6 on 2022-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_alter_product_buyingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BuyingPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
