# Generated by Django 3.2.6 on 2022-02-15 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0017_alter_product_buyingprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('Barcode', models.CharField(blank=True, max_length=15, null=True)),
                ('Image', models.TextField(default='product_photo/default.png', max_length=100)),
                ('Tag', models.CharField(blank=True, max_length=100, null=True)),
                ('Minimum', models.IntegerField(blank=True, null=True)),
                ('BuyingPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('Cost', models.IntegerField(blank=True, null=True)),
                ('Expected_Profit', models.IntegerField(blank=True, null=True)),
                ('Base_Currency', models.CharField(choices=[('B', 'Baht'), ('K', 'Kyat')], default='B', max_length=4)),
                ('Status', models.CharField(choices=[('A', 'Available'), ('N', 'Not available')], default='A', max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Category', models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Product.category')),
                ('Unit', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Product.unit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
