# Generated by Django 3.2.6 on 2022-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_historicalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='MemberPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='RetailPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='MemberPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='RetailPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
