# Generated by Django 3.2.6 on 2022-02-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_auto_20220215_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='MemberPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='RetailPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='MemberPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='RetailPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
