# Generated by Django 3.2.6 on 2022-03-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_auto_20220215_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
