# Generated by Django 3.2.6 on 2022-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_delete_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='BuyingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='BuyingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
