# Generated by Django 3.2.6 on 2022-03-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_auto_20220314_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['ProductName']},
        ),
    ]
