# Generated by Django 3.2.6 on 2022-04-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='BuyingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='BuyingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
