# Generated by Django 3.2.6 on 2022-05-22 15:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_auto_20220402_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=imagekit.models.fields.ProcessedImageField(default='product_photo/default.png', upload_to='product_photo'),
        ),
    ]
