# Generated by Django 2.2.6 on 2021-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='Type',
            field=models.CharField(choices=[('I', 'Inbound'), ('O', 'Outbound')], max_length=10),
        ),
    ]
