# Generated by Django 3.2.6 on 2021-11-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_job_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='OperateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='CreateDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
