# Generated by Django 3.2.6 on 2021-11-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20211123_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Tag',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='Status',
            field=models.CharField(choices=[('W', 'Waiting'), ('C', 'Complete')], default='P', max_length=8),
        ),
    ]
