# Generated by Django 3.2.6 on 2021-11-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20211129_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Barcode',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
