# Generated by Django 3.2.6 on 2021-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20211130_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Product',
            new_name='Inventory',
        ),
        migrations.AlterField(
            model_name='job',
            name='Status',
            field=models.CharField(choices=[('W', 'Waiting'), ('C', 'Complete')], default='W', max_length=8),
        ),
    ]
