# Generated by Django 3.2.6 on 2021-12-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_stockcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcount',
            name='id',
        ),
        migrations.AddField(
            model_name='stockcount',
            name='CountDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='Note',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='Inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.product'),
        ),
    ]
