# Generated by Django 3.2.6 on 2021-12-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20211201_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcount',
            name='LastTransaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
