# Generated by Django 3.2.6 on 2021-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_alter_stockcount_lasttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
