# Generated by Django 3.2.6 on 2021-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_job_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Minimum',
            field=models.IntegerField(default=0),
        ),
    ]
