# Generated by Django 3.2.6 on 2021-12-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Vendor',
        ),
        migrations.AlterField(
            model_name='job',
            name='Customer',
            field=models.CharField(max_length=20),
        ),
    ]
