# Generated by Django 3.2.6 on 2021-12-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_auto_20211210_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Related',
        ),
        migrations.RenameField(
            model_name='related',
            old_name='CustomerName',
            new_name='RelatedName',
        ),
    ]
