# Generated by Django 3.2.6 on 2021-12-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_auto_20211210_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.related'),
        ),
    ]
