# Generated by Django 3.2.6 on 2021-12-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_job_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Customer',
            new_name='Agent',
        ),
    ]
