# Generated by Django 3.2.6 on 2021-12-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_rename_customer_job_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Related',
            new_name='CustomerOrVendor',
        ),
    ]
