# Generated by Django 3.2.6 on 2021-12-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_rename_related_job_customerorvendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Agent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
