# Generated by Django 3.2.6 on 2021-12-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_auto_20211212_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='CustomerOrVendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.related'),
            preserve_default=False,
        ),
    ]
