# Generated by Django 3.2.6 on 2022-01-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.unit'),
            preserve_default=False,
        ),
    ]
