# Generated by Django 3.2.6 on 2022-01-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('Ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.transaction')),
            ],
        ),
    ]
