# Generated by Django 3.2.6 on 2022-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
