# Generated by Django 3.2.6 on 2022-01-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_billing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='Price',
        ),
    ]
