# Generated by Django 3.2.6 on 2022-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_remove_billing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
