# Generated by Django 3.2.6 on 2022-01-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0032_pricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
