# Generated by Django 3.2.6 on 2022-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0034_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Type',
            field=models.CharField(choices=[('I', 'Inbound'), ('O', 'Outbound')], default='O', max_length=10),
        ),
    ]
