# Generated by Django 3.2.6 on 2022-01-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_category'),
        ('warehouse', '0035_alter_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcount',
            name='Inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Product.product'),
        ),
    ]
