# Generated by Django 3.2.6 on 2022-01-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_category'),
        ('warehouse', '0036_alter_stockcount_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
