# Generated by Django 3.2.6 on 2022-01-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0037_alter_transaction_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='related',
            options={'ordering': ['RelatedName']},
        ),
        migrations.AlterField(
            model_name='job',
            name='Photo',
            field=models.ImageField(default='default.png', upload_to='Job_photo'),
        ),
    ]
