# Generated by Django 3.2.6 on 2022-01-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0038_auto_20220118_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Staff',
            field=models.CharField(choices=[('w', 'warehouse'), ('m', 'manager'), ('c', 'cashier')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
