# Generated by Django 3.2.6 on 2022-02-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0039_profile_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
