# Generated by Django 3.2.6 on 2022-02-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0040_auto_20220207_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.job'),
        ),
    ]
