# Generated by Django 3.2.6 on 2022-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0041_alter_transaction_jobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Warehouse',
            field=models.CharField(choices=[('W', 'Warehouse'), ('S', 'Shop')], default='W', max_length=1),
        ),
    ]
