# Generated by Django 3.2.6 on 2022-03-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0042_job_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Description', models.CharField(max_length=30)),
                ('Type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('Amount', models.IntegerField()),
                ('CreateBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
