# Generated by Django 3.2.6 on 2022-03-05 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0043_auto_20220305_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='CreateBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
