# Generated by Django 3.2.6 on 2022-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0044_alter_cashbook_createby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='Type',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='C', max_length=1),
        ),
    ]
