# Generated by Django 3.2.6 on 2022-04-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0045_alter_cashbook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Warehouse',
            field=models.CharField(choices=[('W', 'Warehouse'), ('2', 'Warehouse2'), ('S', 'Shop')], default='W', max_length=1),
        ),
    ]
