# Generated by Django 3.2.6 on 2022-01-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0034_product_price'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Quantity', models.IntegerField()),
                ('Note', models.CharField(max_length=50)),
                ('Inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='PO_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
                ('PO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder')),
            ],
        ),
    ]
