# Generated by Django 3.2.6 on 2022-01-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_po_transaction_receiving'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5)),
                ('Name', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
