# Generated by Django 3.2.6 on 2022-01-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='Destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchase.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Address',
            field=models.CharField(max_length=50),
        ),
    ]
