# Generated by Django 3.2.6 on 2022-01-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20220112_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='Vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchase.vendor'),
            preserve_default=False,
        ),
    ]
