# Generated by Django 3.2.6 on 2022-01-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_receiving_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='receiving',
            name='CarryBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchase.carry'),
            preserve_default=False,
        ),
    ]
