# Generated by Django 3.2.6 on 2022-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20220112_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='Note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='Note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
