# Generated by Django 3.2.6 on 2022-01-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20220116_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='HardCopy',
            field=models.ImageField(default='default.png', upload_to='invoice'),
        ),
    ]
