# Generated by Django 3.2.6 on 2022-01-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_purchaseorder_hardcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='HardCopy',
            field=models.ImageField(default='invoice/default.png', upload_to='invoice'),
        ),
    ]
