# Generated by Django 3.2.6 on 2022-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_purchaseorder_hardcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='Contact',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Contact',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
