# Generated by Django 3.2.6 on 2022-02-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_auto_20220122_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(default='invoice/default.png', upload_to='invoice')),
                ('PO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder')),
            ],
        ),
    ]
