# Generated by Django 3.2.6 on 2022-02-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_hardcopy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='HardCopy',
        ),
    ]
