# Generated by Django 3.2.6 on 2022-02-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_remove_purchaseorder_hardcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='CreateDate',
            field=models.DateTimeField(),
        ),
    ]
