# Generated by Django 3.2.6 on 2022-02-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_alter_purchaseorder_createdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='CreateDate',
            new_name='OrderDate',
        ),
    ]
