# Generated by Django 3.2.6 on 2022-02-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_rename_createdate_purchaseorder_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='OrderDate',
            field=models.DateField(),
        ),
    ]
