# Generated by Django 3.2.6 on 2022-02-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_alter_purchaseorder_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='OrderDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
