# Generated by Django 3.2.6 on 2022-02-19 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_alter_purchaseorder_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='OrderDate',
            field=models.DateField(default=datetime.date(2022, 2, 19)),
        ),
    ]
