# Generated by Django 3.2.6 on 2022-02-19 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_alter_purchaseorder_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 2, 19, 11, 57, 16, 322195, tzinfo=utc)),
        ),
    ]
