# Generated by Django 3.2.6 on 2022-02-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_alter_purchaseorder_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='OrderDate',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.IntegerField()),
                ('Note', models.CharField(max_length=50)),
                ('Type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=6)),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.vendor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
