# Generated by Django 3.2.6 on 2022-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_auto_20220219_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
