# Generated by Django 3.2.6 on 2022-02-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_account_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Date',
            new_name='AccountDate',
        ),
    ]
