# Generated by Django 3.2.6 on 2022-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_rename_date_account_accountdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
