# Generated by Django 3.2.6 on 2022-02-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0041_alter_transaction_jobid'),
        ('purchase', '0025_alter_account_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Related',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.related'),
        ),
    ]
