# Generated by Django 3.2.6 on 2022-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0026_vendor_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_transaction',
            name='Price',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
