# Generated by Django 3.2.6 on 2022-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0027_alter_po_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_transaction',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
