# Generated by Django 3.2.6 on 2022-03-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0028_alter_po_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Photo',
            field=models.ImageField(default='invoice/default.png', upload_to='paymentslip'),
        ),
    ]
