# Generated by Django 3.2.6 on 2022-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0029_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='Status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='O', max_length=5),
        ),
    ]
