# Generated by Django 3.2.6 on 2022-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0030_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Photo',
            field=models.ImageField(upload_to='paymentslip'),
        ),
    ]
