# Generated by Django 3.2.6 on 2022-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0031_alter_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='paymentslip'),
        ),
    ]
