# Generated by Django 3.2.6 on 2022-04-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0032_alter_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Type',
            field=models.CharField(choices=[('D', 'Debit-'), ('C', 'Credit+')], default='C', max_length=6),
        ),
    ]
