# Generated by Django 3.2.6 on 2022-04-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0033_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='Currency',
            field=models.CharField(choices=[('B', 'Baht'), ('K', 'Kyat')], default='B', max_length=5),
        ),
    ]
