# Generated by Django 3.2.6 on 2022-03-15 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complete', models.BooleanField(default=False)),
                ('Todo', models.CharField(max_length=100)),
                ('Related', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
