# Generated by Django 3.2.6 on 2022-03-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=45)),
                ('ProfilePhoto', models.ImageField(default='employee/default.png', upload_to='employee')),
                ('Active', models.BooleanField(default=True)),
                ('Position', models.CharField(choices=[('M', 'Manager'), ('S', 'Supervisor'), ('G', 'General Staff')], max_length=1)),
            ],
        ),
    ]
