# Generated by Django 3.2.6 on 2022-01-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Note', models.CharField(blank=True, max_length=50, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='SO_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.product')),
                ('SO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Note', models.CharField(max_length=50)),
                ('Type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=6)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.buyer')),
            ],
        ),
    ]
