# Generated by Django 3.2.6 on 2022-01-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
