# Generated by Django 3.2.6 on 2022-01-18 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_account_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='Currency',
            field=models.CharField(choices=[('B', 'Baht'), ('K', 'Kyat')], default='B', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
