# Generated by Django 3.2.6 on 2022-01-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20220118_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='Status',
        ),
    ]
