# Generated by Django 3.2.6 on 2022-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='Status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='O', max_length=5),
            preserve_default=False,
        ),
    ]
