# Generated by Django 3.2.6 on 2022-01-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='Pricelist',
            field=models.CharField(choices=[(1, 'Retail'), (2, 'Member')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
