# Generated by Django 3.2.6 on 2022-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_buyer_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='Pricelist',
            field=models.CharField(choices=[('1', 'Retail'), ('2', 'Member')], default='1', max_length=6),
        ),
    ]
