# Generated by Django 3.2.6 on 2022-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_account_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='Pricelist',
            field=models.CharField(choices=[('1', 'Retail'), ('2', 'Member')], max_length=6),
        ),
    ]
