# Generated by Django 3.2.6 on 2022-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_buyer_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='Status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='O', max_length=5),
        ),
    ]
