# Generated by Django 3.2.6 on 2023-04-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='Pay',
            field=models.IntegerField(default=0),
        ),
    ]
