# Generated by Django 3.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_salesorder_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='CreateDate',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
